# Site settings
title: leetcode
email: yingmingfan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site was written for my leetcode practice.
baseurl: "/leetcode" # the subpath of your site, e.g. /blog/
url: "http://yingming.me" # the base hostname & protocol for your site
twitter_username: YingmingFan
github_username:  fanyingming

# Build settings
markdown: kramdown
